/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.sisventas.model.presentacion;

import com.sisventas.model.beans.Venta;
import com.sisventas.model.logic.VentaLogic;
import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jean Paul
 */
public class FrmConsultarVenta extends javax.swing.JDialog {
    private ImageIcon imagen;
    private Icon icono;
    private Border border = BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLACK);
    private Border border1 = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.RED);
    /**
     * Creates new form FrmConsultarVenta
     */
    public FrmConsultarVenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        cargarTablaVenta();
        cargarComboFecha();
        cmbfecha.setVisible(false);
        txtbuscador.setVisible(false);
        this.pintarImagen(lblfondo, "src/imagenes/fondop.jpg");
        this.pintarImagen(lblpc, "src/imagenes/ventasrea.jpg");
        txtbuscador.setBorder(border1);
        jPanel1.setBorder(border);
        jScrollPane1.setBorder(border);
    }
    
    private void cargarTablaVenta(){
        tableModel = VentaLogic.tableModelVentas();
        tblventas.setModel(tableModel);
    }
    
    private void cargarComboFecha(){
        comboModel = VentaLogic.comboModelVenta();
        cmbfecha.setModel(comboModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        op = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtbuscador = new javax.swing.JTextField();
        btnfiltrar = new javax.swing.JButton();
        cmbfecha = new javax.swing.JComboBox<>();
        btnitemnombre = new javax.swing.JRadioButton();
        btnitemfecha = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btnregresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblventas = new javax.swing.JTable();
        lblpc = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtbuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 224, -1));

        btnfiltrar.setBackground(new java.awt.Color(255, 255, 255));
        btnfiltrar.setForeground(new java.awt.Color(0, 0, 0));
        btnfiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarp.png"))); // NOI18N
        btnfiltrar.setText("Filtrar");
        btnfiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfiltrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnfiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        cmbfecha.setBackground(new java.awt.Color(52, 142, 201));
        cmbfecha.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(cmbfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 224, -1));

        op.add(btnitemnombre);
        btnitemnombre.setForeground(new java.awt.Color(0, 0, 0));
        btnitemnombre.setText("Nombre del Cliente");
        btnitemnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnitemnombreActionPerformed(evt);
            }
        });
        jPanel1.add(btnitemnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        op.add(btnitemfecha);
        btnitemfecha.setForeground(new java.awt.Color(0, 0, 0));
        btnitemfecha.setText("Fecha de venta");
        btnitemfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnitemfechaActionPerformed(evt);
            }
        });
        jPanel1.add(btnitemfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 420, 150));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ventas Realizadas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 320, -1));

        btnregresar.setBackground(new java.awt.Color(255, 255, 255));
        btnregresar.setForeground(new java.awt.Color(0, 0, 0));
        btnregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras (1).png"))); // NOI18N
        btnregresar.setText("Regresar");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        tblventas.setBackground(new java.awt.Color(255, 255, 255));
        tblventas.setForeground(new java.awt.Color(0, 0, 0));
        tblventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblventas.setSelectionBackground(new java.awt.Color(153, 255, 153));
        tblventas.setSelectionForeground(new java.awt.Color(0, 0, 153));
        jScrollPane1.setViewportView(tblventas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 540, 209));
        getContentPane().add(lblpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 190, 190));
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiltrarActionPerformed
        if(btnitemfecha.isSelected()){
            Venta venta = (Venta) cmbfecha.getSelectedItem();
            String nombre = venta.toString();
            tableModel = VentaLogic.tableModelBuscadorVentas(nombre);
            tblventas.setModel(tableModel);
        }else if(btnitemnombre.isSelected()){
            String nombre = txtbuscador.getText();
            tableModel = VentaLogic.tableModelBuscadorVentas(nombre);
            tblventas.setModel(tableModel);
        }
    }//GEN-LAST:event_btnfiltrarActionPerformed

    private void btnitemfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnitemfechaActionPerformed
        cmbfecha.setVisible(true);
        txtbuscador.setVisible(false);
        
    }//GEN-LAST:event_btnitemfechaActionPerformed

    private void btnitemnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnitemnombreActionPerformed
        txtbuscador.setVisible(true);
        cmbfecha.setVisible(false);
    }//GEN-LAST:event_btnitemnombreActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConsultarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConsultarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConsultarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConsultarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmConsultarVenta dialog = new FrmConsultarVenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void pintarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lbl.getWidth(),lbl.getHeight(),Image.SCALE_DEFAULT));
        lbl.setIcon(this.icono);
        this.repaint();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfiltrar;
    private javax.swing.JRadioButton btnitemfecha;
    private javax.swing.JRadioButton btnitemnombre;
    private javax.swing.JButton btnregresar;
    private javax.swing.JComboBox<String> cmbfecha;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblpc;
    private javax.swing.ButtonGroup op;
    private javax.swing.JTable tblventas;
    private javax.swing.JTextField txtbuscador;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel tableModel;
    private DefaultComboBoxModel comboModel;
}
