/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.sisventas.model.presentacion;

import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import com.sisventas.model.logic.UsuarioLogic;

/**
 *
 * @author Jean Paul
 */
public class FrmLogin extends javax.swing.JDialog {
    private ImageIcon imagen;
    private Icon icono;
    private Border border = BorderFactory.createMatteBorder(0, 0, 3, 1, Color.red);
    private Border border1 = BorderFactory.createMatteBorder(0, 0, 4, 4, Color.BLUE);
    /**
     * Creates new form FrmLogin
     */
    public FrmLogin(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        jPanel1.setBackground(Color.white);
        jPanel1.setBorder(border1);
        lblerror.setVisible(false);
        txtusuario.setBorder(border);
        txtcontraseña.setBorder(border);
        this.pintarImagen(lblusuario, "src/imagenes/usuario (1).png");
        this.pintarImagen(lblcontraeña, "src/imagenes/contrasena.png");
        this.pintarImagen(lblfondo, "src/imagenes/fondop.jpg");
        this.pintarImagen(lblfondousuario, "src/imagenes/usuario.png");
        this.pintarImagen(lblfond, "src/imagenes/fond.png");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblfond = new javax.swing.JLabel();
        lblfondousuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtusuario = new javax.swing.JTextField();
        lblusuario = new javax.swing.JLabel();
        txtcontraseña = new javax.swing.JPasswordField();
        lblcontraeña = new javax.swing.JLabel();
        lblerror = new javax.swing.JLabel();
        btningresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblregistrar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnregresar = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblfond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 330, 330));
        getContentPane().add(lblfondousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 130, 120));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(153, 153, 153));
        txtusuario.setText("usuario");
        txtusuario.setCaretColor(new java.awt.Color(255, 0, 0));
        txtusuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusuarioFocusLost(evt);
            }
        });
        jPanel1.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 133, 30));
        jPanel1.add(lblusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 50, 50));

        txtcontraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcontraseña.setForeground(new java.awt.Color(153, 153, 153));
        txtcontraseña.setText("contraseña");
        txtcontraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcontraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcontraseñaFocusLost(evt);
            }
        });
        jPanel1.add(txtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 133, 30));
        jPanel1.add(lblcontraeña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 50, 50));

        lblerror.setForeground(new java.awt.Color(255, 0, 0));
        lblerror.setText("Usuario o contraseña incorrecto.");
        jPanel1.add(lblerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 216, -1, 20));

        btningresar.setBackground(new java.awt.Color(255, 255, 255));
        btningresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btningresar.setForeground(new java.awt.Color(0, 0, 255));
        btningresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iniciar-sesion.png"))); // NOI18N
        btningresar.setText("Ingresar");
        btningresar.setBorder(null);
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });
        jPanel1.add(btningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 130, 60));

        jLabel1.setText("¿No tienes una cuenta?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 20));

        lblregistrar.setForeground(new java.awt.Color(0, 0, 204));
        lblregistrar.setText("<html><u>Regístrate</u></html>");
        lblregistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblregistrarMouseClicked(evt);
            }
        });
        jPanel1.add(lblregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 32)); // NOI18N
        jLabel2.setText("Iniciar Sesión:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 220, 40));

        btnregresar.setBackground(new java.awt.Color(255, 255, 255));
        btnregresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnregresar.setForeground(new java.awt.Color(0, 0, 255));
        btnregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion (2).png"))); // NOI18N
        btnregresar.setText("Salir");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 360, 370));

        lblfondo.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusuarioFocusLost
        if(txtusuario.getText().trim().equals("") || txtusuario.getText().trim().toLowerCase().equals("usuario")){
            txtusuario.setText("usuario");
            txtusuario.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_txtusuarioFocusLost

    private void txtusuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusuarioFocusGained
        if(txtusuario.getText().trim().toLowerCase().equals("usuario")){
            txtusuario.setText("");
            txtusuario.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtusuarioFocusGained

    private void txtcontraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontraseñaFocusGained
        String contraseña = String.valueOf(txtcontraseña.getPassword());
        if(contraseña.trim().toLowerCase().equals("contraseña")){
            txtcontraseña.setText("");
            txtcontraseña.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtcontraseñaFocusGained

    private void txtcontraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontraseñaFocusLost
        String contraseña = String.valueOf(txtcontraseña.getPassword());
        if(contraseña.trim().equals("") || contraseña.trim().toLowerCase().equals("contraseña")){
            txtcontraseña.setText("contraseña");
            txtcontraseña.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtcontraseñaFocusLost

    private void lblregistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregistrarMouseClicked
        FrmRegistro registro = new FrmRegistro(new javax.swing.JDialog(), true);
        registro.setVisible(true);
    }//GEN-LAST:event_lblregistrarMouseClicked

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        try {
            String usuario = txtusuario.getText();
            String contraseña = String.valueOf(txtcontraseña.getPassword());
            if(usuario.isEmpty() || contraseña.isEmpty() || contraseña.equals("contraseña") || usuario.equals("usuario")){
                JOptionPane.showMessageDialog(this, "Por favor, llene los campos");
            
            }else{
                if(UsuarioLogic.obtenerUsuario(usuario).getContraseña().equals(contraseña)){
                    this.dispose();
                    FrmPrincipal principal = new FrmPrincipal();
                    principal.setVisible(true);
                }else{
                    lblerror.setVisible(true);
                    txtusuario.setText("");
                    txtcontraseña.setText("");
                }
            }
        } catch (Exception ex) {
            lblerror.setVisible(true);
            txtusuario.setText("");
            txtcontraseña.setText("");
        }
    }//GEN-LAST:event_btningresarActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmLogin dialog = new FrmLogin(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private void pintarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lbl.getWidth(),lbl.getHeight(),Image.SCALE_DEFAULT));
        lbl.setIcon(this.icono);
        this.repaint();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btningresar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcontraeña;
    private javax.swing.JLabel lblerror;
    private javax.swing.JLabel lblfond;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblfondousuario;
    private javax.swing.JLabel lblregistrar;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
