/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sisventas.model.presentacion;

import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.border.Border;

/**
 *
 * @author Jean Paul
 */
public class FrmPrincipal extends javax.swing.JFrame {
    private ImageIcon imagen;
    private Icon icono;
    private Border border1 = BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLACK);
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pintarImagen(lblfondo, "src/imagenes/fondop.jpg");
        this.pintarImagen(lbl4tel, "src/imagenes/4telefonos.png");
        this.pintarImagen(lblmov, "src/imagenes/s21.png");
        this.pintarImagen(lblacc, "src/imagenes/accesorios.png");
        jPanel1.setBorder(border1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btniniciarventa = new javax.swing.JButton();
        btnbuscarproducto = new javax.swing.JButton();
        btnconsultarventa = new javax.swing.JButton();
        btnbuscarcliente = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        lblmov = new javax.swing.JLabel();
        lblacc = new javax.swing.JLabel();
        lbl4tel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuitemregproducto = new javax.swing.JMenu();
        mnuitemregprod = new javax.swing.JMenuItem();
        mnuitemregistrarcliente = new javax.swing.JMenuItem();
        mnuitemregcategoria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(81, 222, 73));
        jPanel1.setForeground(new java.awt.Color(203, 193, 193));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btniniciarventa.setBackground(new java.awt.Color(255, 255, 255));
        btniniciarventa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btniniciarventa.setForeground(new java.awt.Color(0, 0, 0));
        btniniciarventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas.png"))); // NOI18N
        btniniciarventa.setText("Iniciar Venta");
        btniniciarventa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btniniciarventaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btniniciarventaMouseExited(evt);
            }
        });
        btniniciarventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniniciarventaActionPerformed(evt);
            }
        });
        jPanel1.add(btniniciarventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, -1));

        btnbuscarproducto.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscarproducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnbuscarproducto.setForeground(new java.awt.Color(0, 0, 0));
        btnbuscarproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto.png"))); // NOI18N
        btnbuscarproducto.setText("Buscar Producto");
        btnbuscarproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbuscarproductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbuscarproductoMouseExited(evt);
            }
        });
        btnbuscarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarproductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscarproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, -1));

        btnconsultarventa.setBackground(new java.awt.Color(255, 255, 255));
        btnconsultarventa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnconsultarventa.setForeground(new java.awt.Color(0, 0, 0));
        btnconsultarventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/terminal-pos.png"))); // NOI18N
        btnconsultarventa.setText("Consultar Ventas");
        btnconsultarventa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnconsultarventaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnconsultarventaMouseExited(evt);
            }
        });
        btnconsultarventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarventaActionPerformed(evt);
            }
        });
        jPanel1.add(btnconsultarventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        btnbuscarcliente.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscarcliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnbuscarcliente.setForeground(new java.awt.Color(0, 0, 0));
        btnbuscarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscando.png"))); // NOI18N
        btnbuscarcliente.setText("Buscar Cliente");
        btnbuscarcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbuscarclienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbuscarclienteMouseExited(evt);
            }
        });
        btnbuscarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarclienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 260, 310));

        btnsalir.setBackground(new java.awt.Color(255, 255, 255));
        btnsalir.setForeground(new java.awt.Color(0, 0, 0));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion (2).png"))); // NOI18N
        btnsalir.setText("Cerrar Sesion");
        btnsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsalirMouseExited(evt);
            }
        });
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, 60));
        getContentPane().add(lblmov, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 180, 280));
        getContentPane().add(lblacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 220, 180));
        getContentPane().add(lbl4tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 190, 130));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("¿Que operación vamos a realizar?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 570, 59));
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 480));

        mnuitemregproducto.setBackground(new java.awt.Color(255, 255, 255));
        mnuitemregproducto.setForeground(new java.awt.Color(0, 0, 0));
        mnuitemregproducto.setText("Registro");
        mnuitemregproducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mnuitemregprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja.png"))); // NOI18N
        mnuitemregprod.setText("Registrar Producto");
        mnuitemregprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemregprodActionPerformed(evt);
            }
        });
        mnuitemregproducto.add(mnuitemregprod);

        mnuitemregistrarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/kyc.png"))); // NOI18N
        mnuitemregistrarcliente.setText("Registrar Cliente");
        mnuitemregistrarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemregistrarclienteActionPerformed(evt);
            }
        });
        mnuitemregproducto.add(mnuitemregistrarcliente);

        mnuitemregcategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/categorias.png"))); // NOI18N
        mnuitemregcategoria.setText("Registrar Categoria");
        mnuitemregcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemregcategoriaActionPerformed(evt);
            }
        });
        mnuitemregproducto.add(mnuitemregcategoria);

        jMenuBar1.add(mnuitemregproducto);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuitemregprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemregprodActionPerformed
        FrmRegistrarProducto frmpro = new FrmRegistrarProducto(this, true);
        frmpro.setVisible(true);
        
    }//GEN-LAST:event_mnuitemregprodActionPerformed

    private void mnuitemregcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemregcategoriaActionPerformed
        FrmRegistrarCategoria frmcat = new FrmRegistrarCategoria(this, true);
        frmcat.setVisible(true);
    }//GEN-LAST:event_mnuitemregcategoriaActionPerformed

    private void mnuitemregistrarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemregistrarclienteActionPerformed
        FrmRegistrarCliente frmclie = new FrmRegistrarCliente(this, true);
        frmclie.setVisible(true);
    }//GEN-LAST:event_mnuitemregistrarclienteActionPerformed

    private void btniniciarventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniniciarventaActionPerformed
        FrmIniciarVenta frminiciar = new FrmIniciarVenta(this, true);
        frminiciar.setVisible(true);
    }//GEN-LAST:event_btniniciarventaActionPerformed

    private void btnbuscarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarproductoActionPerformed
        FrmBuscarProducto frmbuscar = new FrmBuscarProducto(this, true);
        frmbuscar.setVisible(true);
    }//GEN-LAST:event_btnbuscarproductoActionPerformed

    private void btnconsultarventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarventaActionPerformed
        FrmConsultarVenta frmcons = new FrmConsultarVenta(this, true);
        frmcons.setVisible(true);
    }//GEN-LAST:event_btnconsultarventaActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnbuscarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarclienteActionPerformed
        FrmBuscarCliente frmconsc = new FrmBuscarCliente(this, true);
        frmconsc.setVisible(true);
    }//GEN-LAST:event_btnbuscarclienteActionPerformed

    private void btniniciarventaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btniniciarventaMouseEntered
        btniniciarventa.setBackground(new Color(50,199,236));
    }//GEN-LAST:event_btniniciarventaMouseEntered

    private void btniniciarventaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btniniciarventaMouseExited
        btniniciarventa.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btniniciarventaMouseExited

    private void btnbuscarproductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarproductoMouseEntered
        btnbuscarproducto.setBackground(new Color(50,199,236));
    }//GEN-LAST:event_btnbuscarproductoMouseEntered

    private void btnbuscarproductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarproductoMouseExited
        btnbuscarproducto.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnbuscarproductoMouseExited

    private void btnconsultarventaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconsultarventaMouseEntered
        btnconsultarventa.setBackground(new Color(50,199,236));
    }//GEN-LAST:event_btnconsultarventaMouseEntered

    private void btnconsultarventaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconsultarventaMouseExited
        btnconsultarventa.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnconsultarventaMouseExited

    private void btnbuscarclienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarclienteMouseEntered
        btnbuscarcliente.setBackground(new Color(50,199,236));
    }//GEN-LAST:event_btnbuscarclienteMouseEntered

    private void btnbuscarclienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarclienteMouseExited
        btnbuscarcliente.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnbuscarclienteMouseExited

    private void btnsalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseEntered
        
    }//GEN-LAST:event_btnsalirMouseEntered

    private void btnsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseExited
        
    }//GEN-LAST:event_btnsalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
    
    private void pintarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lbl.getWidth(),lbl.getHeight(),Image.SCALE_DEFAULT));
        lbl.setIcon(this.icono);
        this.repaint();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscarcliente;
    private javax.swing.JButton btnbuscarproducto;
    private javax.swing.JButton btnconsultarventa;
    private javax.swing.JButton btniniciarventa;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl4tel;
    private javax.swing.JLabel lblacc;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblmov;
    private javax.swing.JMenuItem mnuitemregcategoria;
    private javax.swing.JMenuItem mnuitemregistrarcliente;
    private javax.swing.JMenuItem mnuitemregprod;
    private javax.swing.JMenu mnuitemregproducto;
    // End of variables declaration//GEN-END:variables
}
