/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.sisventas.model.presentacion;

import javax.swing.JOptionPane;
import com.sisventas.model.beans.Usuario;
import com.sisventas.model.logic.UsuarioLogic;
import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.border.Border;

/**
 *
 * @author Jean Paul
 */
public class FrmRegistro extends javax.swing.JDialog {
    private ImageIcon imagen;
    private Icon icono;
    private Border border = BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLACK);
    private Border border1 = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.RED);
    
    /**
     * Creates new form FrmRegistro
     */
    public FrmRegistro(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        lblusuario.setVisible(false);
        lblcontraseña.setVisible(false);
        jPanel1.setBorder(border);
        this.pintarImagen(lblfondo, "src/imagenes/fondoregistro.jpg");
        txtdni.setBorder(border1);
        txtusuario.setBorder(border1);
        txtcontra1.setBorder(border1);
        txtcontra2.setBorder(border1);
        this.pintarImagen(lblpc, "src/imagenes/computadora.png");
        this.pintarImagen(lblfondo2, "src/imagenes/fondoT.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblpc = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        lblusuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcontra1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtcontra2 = new javax.swing.JPasswordField();
        lblcontraseña = new javax.swing.JLabel();
        btnregistrar = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        lblfondo2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 130, 100));

        jPanel1.setBackground(new java.awt.Color(85, 187, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("DNI:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        txtdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdniKeyTyped(evt);
            }
        });
        jPanel1.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 173, -1));

        jLabel4.setText("Usuario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        jPanel1.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 173, -1));

        lblusuario.setForeground(new java.awt.Color(255, 0, 0));
        lblusuario.setText("Usuario ya existe");
        jPanel1.add(lblusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));
        jPanel1.add(txtcontra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 173, -1));

        jLabel6.setText("Confirmar contraseña:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));
        jPanel1.add(txtcontra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 173, -1));

        lblcontraseña.setForeground(new java.awt.Color(255, 0, 0));
        lblcontraseña.setText("Contraseñas incorrectas, vuelva a intentarlo ");
        jPanel1.add(lblcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        btnregistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnregistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verificar (1).png"))); // NOI18N
        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, 40));

        btnvolver.setBackground(new java.awt.Color(255, 255, 255));
        btnvolver.setForeground(new java.awt.Color(0, 0, 0));
        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras (1).png"))); // NOI18N
        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 370, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 330, 450));
        getContentPane().add(lblfondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 380, 220));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(214, 7, 7));
        jLabel1.setText("Romero");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 150, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(214, 7, 7));
        jLabel7.setText("Telecomunicaciones");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 360, -1));
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        try {
            int dni = Integer.parseInt(txtdni.getText());
            String usuario = txtusuario.getText();
            String contraseña1 = String.valueOf(txtcontra1.getPassword());
            String contraseña2 = String.valueOf(txtcontra2.getPassword());
            if(usuario.isEmpty() || contraseña1.isEmpty() || contraseña2.isEmpty()){
                JOptionPane.showMessageDialog(this, "Llene todos los campos");
            }else{
                if(contraseña1.equals(contraseña2)){
                    Usuario usuario1 = new Usuario(dni, usuario, contraseña1);
                    if(UsuarioLogic.insertarUsuario(usuario1)){
                        JOptionPane.showMessageDialog(this, "Registro completado, vuelva a iniciar sesion");
                        this.dispose();
                    }else{
                        lblusuario.setVisible(true);
                        txtusuario.setText("");
                        txtcontra1.setText("");
                        txtcontra2.setText("");
                    }
                }else{
                    lblcontraseña.setVisible(true);
                    txtcontra1.setText("");
                    txtcontra2.setText("");
                }
                
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Llene todos los campos");
        }
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnvolverActionPerformed

    private void txtdniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
            evt.consume();
    }//GEN-LAST:event_txtdniKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRegistro dialog = new FrmRegistro(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private void pintarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lbl.getWidth(),lbl.getHeight(),Image.SCALE_DEFAULT));
        lbl.setIcon(this.icono);
        this.repaint();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblfondo2;
    private javax.swing.JLabel lblpc;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPasswordField txtcontra1;
    private javax.swing.JPasswordField txtcontra2;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
